name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Coverage
        run: pip install coverage
      - name: Install Dependencies
        run:
          sudo apt-get install -y xvfb
      - name: Code Coverage with Coveralls
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Run Tests
        run: coverage run --source=. -m unittest discover -s . -p "TestApp.py"
